config/routes.rb
Rails.application.routes.draw do
  root 'users#home'
  resources :restaurants
  resources :likeds
  resources :restaurant_events
  resources :events
  resources :user_events
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :likeds
  has_many :user_events
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  def home
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :age, :gender, :location, :password, :fav_meal, :availability)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
  <div id="error_explanation">
  <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
  
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
        </ul>
        </div>
        <% end %>
        
        <div class="form-group">
        <%= form.label :name %>
        <input type="text" name="user[name]" id="user_name" class="form-control">
        </div>
        
        <div class="form-group">
        <%= form.label :email %>
        <input type="text" name="user[email]" id="user_email" class="form-control">
        </div>
        
        <div class="form-group">
        <%= form.label :age %>
        <input type="number" name="user[age]" id="user_age" class="form-control">
        </div>
        
        <div class="form-group">
        <%= form.label :gender %>
        <input type="text" name="user[gender]" id="user_gender" class="form-control">        
        </div>
        
        <div class="form-group">
        <%= form.label :location %>
        <input type="text" name="user[location]" id="user_location" class="form-control">
    </div>
    
  <div class="form-group">
  <%= form.label :password %>
  <input type="password" name="user[password]" id="user_password" class="form-control">
    </div>
  
  <div class="form-group">
  <%= form.label :fav_meal %>
  <input type="text" name="user[fav_meal]" id="user_fav_meal" class="form-control">
    </div>
  
  <div class="form-group">
  <%= form.label :availability %>
  <input type="text" name="user[availability]" id="user_availability" class="form-control">
    </div>
  
  <button class="btn btn-success" type="submit">
  Submit
  </button>
  <% end %>
  </div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/home.html.erb
<%= stylesheet_link_tag "style.css" %>
<div class="container" style="width: 450px">
<img src="https://cdn.discordapp.com/attachments/599659573594423309/599731501273186306/big-logo.png" style="width: 400px" />
<br>
<div class="styless">
<%= link_to 'Create an Account', new_user_path %> |
<%= link_to 'Login', root_path %>
</div>
</div>

app/views/users/index.html.erb
<%= stylesheet_link_tag "style.css" %>
<div class="container">
<div class="card rounded" style="width: 100%; padding:20px; margin: 20px; background: white">
  <div class="card-body">
    <h1 class="card-title">Users
</h1>
<p id="notice"><%= notice %></p>



<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Location</th>
      <th>Password</th>
      <th>Fav meal</th>
      <th>Availability</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.age %></td>
        <td><%= user.gender %></td>
        <td><%= user.location %></td>
        <td><%= user.password %></td>
        <td><%= user.fav_meal %></td>
        <td><%= user.availability %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= stylesheet_link_tag "style.css" %>
<div class="container">
<div class="card rounded" style="width: 30rem; padding:20px; background: white">
  <div class="card-body">
    <h1 class="card-title">New User
</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %> |
<%= link_to 'Login instead', root_path %>


</div>
</div>
</div>

app/views/users/show.html.erb
<%= stylesheet_link_tag "style.css" %>
<div class="container">
<div class="card rounded" style="width: 30rem; padding:20px; background: white">
  <div class="card-body">
    <h1 class="card-title">Welcome!
</h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<p>
  <strong>Location:</strong>
  <%= @user.location %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Fav meal:</strong>
  <%= @user.fav_meal %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @user.availability %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %> |
<%= link_to 'Restaurants', restaurants_path %> |
<%= link_to 'Events', events_path %>


</div>
</div>
</div>