config/routes.rb
Rails.application.routes.draw do
  root 'users#home'
  resources :restaurants
  resources :likeds
  resources :restaurant_events
  resources :events
  resources :user_events
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :user_events
  has_many :restaurant_events
  has_many :users , through: :user_events
  has_many :restaurants, through: :restaurant_events

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :user_event_id, :restaurant_event_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <input type="text" name="event[name]" id="event_name" class="form-control">
  </div>

  <div class="form-group">
    <%= form.label :user_event_id %>
    <input type="number" name="event[user_event_id]" id="event_user_event_id" class="form-control">
  </div>

  <div class="form-group">
    <%= form.label :restaurant_event_id %>
    <input type="number" name="event[restaurant_event_id]" id="event_restaurant_event_id" class="form-control">
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<%= stylesheet_link_tag "style.css" %>
<div class="container">
<div class="card rounded" style="width: 50rem; padding:20px; margin: 20px; background: white">
  <div class="card-body">
    <h1 class="card-title">Events
</h1>
<p id="notice"><%= notice %></p>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User event</th>
      <th>Restaurant event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %> |
<%= link_to 'Back', users_path %> |
<%= link_to 'Home', root_path %> |
<%= link_to 'Restaurants', restaurants_path %>

app/views/events/new.html.erb
<%= stylesheet_link_tag "style.css" %>
<div class="container">
<div class="card rounded" style="width: 50rem; padding:20px; margin: 20px;background: white">
  <div class="card-body">
    <h1 class="card-title">New Event
</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>User event:</strong>
  <%= @event.user_event_id %>
</p>

<p>
  <strong>Restaurant event:</strong>
  <%= @event.restaurant_event_id %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>