config/routes.rb
Rails.application.routes.draw do
  root 'users#home'
  resources :restaurants
  resources :likeds
  resources :restaurant_events
  resources :events
  resources :user_events
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :likeds
  has_many :users, through: :likeds
  has_many :restaurant_events
  
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :cuisine, :like_id, :zipcode, :restaurant_event_id)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <input type="text" name="restaurant[name]" class="form-control" id="restaurant_name">
  </div>

  <div class="form-group">
    <%= form.label :cuisine %>
    <input type="text" name="restaurant[cuisine]" class="form-control" id="restaurant_cuisine">
  </div>

  <div class="form-group">
    <%= form.label :like_id %>
    <input type="number" name="restaurant[like_id]" class="form-control" id="restaurant_like_id">
  </div>

  <div class="form-group">
    <%= form.label :zipcode %>
    <input type="number" name="restaurant[zipcode]" class="form-control" id="restaurant_zipcode">
  </div>

  <div class="form-group">
    <%= form.label :restaurant_event_id %>
    <input type="number" name="restaurant[restaurant_event_id]" class="form-control" id="restaurant_restaurant_event_id">
  </div>

  <button class="btn btn-success" type="submit">
  Submit
  </button>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<%= stylesheet_link_tag "style.css" %>
<div class="container">
<div class="card rounded" style="width: 100%; padding:20px; margin:20px; background: white">
  <div class="card-body">
    <h1 class="card-title">Restaurants
</h1>
<p id="notice"><%= notice %></p>



<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cuisine</th>
      <th>Like</th>
      <th>Zipcode</th>
      <th>Restaurant event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.cuisine %></td>
        <td><input type="checkbox" name="like" value="like"></td>
        <td><%= restaurant.zipcode %></td>
        <td><%= restaurant.restaurant_event_id %></td>
        <td><%= link_to 'Show', restaurant %></td> 
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td> 
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %> |
<%= link_to 'Back', users_path %> |
<%= link_to 'Home', root_path %> |
<%= link_to 'Events', events_path %> |
<%= link_to 'Save Likes', likeds_path %>

app/views/restaurants/new.html.erb
<%= stylesheet_link_tag "style.css" %>
<div class="container">
<div class="card rounded" style="width: 50rem; padding:20px; margin:20px; background: white">
  <div class="card-body">
    <h1 class="card-title">New Restaurant
</h1>


<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<%= stylesheet_link_tag "style.css" %>
<div class="container">
<div class="card rounded" style="width: 30rem; padding:20px; background: white">
  <div class="card-body">
    <h1 class="card-title">Current Restaurants
</h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Cuisine:</strong>
  <%= @restaurant.cuisine %>
</p>

<p>
  <strong>Like:</strong>
  <%= @restaurant.like_id %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @restaurant.zipcode %>
</p>

<p>
  <strong>Restaurant event:</strong>
  <%= @restaurant.restaurant_event_id %>
</p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>

</div>
</div>
</div>