config/routes.rb
Rails.application.routes.draw do
  root 'users#home'
  resources :restaurants
  resources :likeds
  resources :restaurant_events
  resources :events
  resources :user_events
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/liked.rb
class Liked < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/controllers/likeds_controller.rb
class LikedsController < ApplicationController
  before_action :set_liked, only: [:show, :edit, :update, :destroy]

  # GET /likeds
  # GET /likeds.json
  def index
    @likeds = Liked.all
  end

  # GET /likeds/1
  # GET /likeds/1.json
  def show
  end

  # GET /likeds/new
  def new
    @liked = Liked.new
  end

  # GET /likeds/1/edit
  def edit
  end

  # POST /likeds
  # POST /likeds.json
  def create
    @liked = Liked.new(liked_params)

    respond_to do |format|
      if @liked.save
        format.html { redirect_to @liked, notice: 'Liked was successfully created.' }
        format.json { render :show, status: :created, location: @liked }
      else
        format.html { render :new }
        format.json { render json: @liked.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /likeds/1
  # PATCH/PUT /likeds/1.json
  def update
    respond_to do |format|
      if @liked.update(liked_params)
        format.html { redirect_to @liked, notice: 'Liked was successfully updated.' }
        format.json { render :show, status: :ok, location: @liked }
      else
        format.html { render :edit }
        format.json { render json: @liked.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likeds/1
  # DELETE /likeds/1.json
  def destroy
    @liked.destroy
    respond_to do |format|
      format.html { redirect_to likeds_url, notice: 'Liked was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_liked
      @liked = Liked.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def liked_params
      params.require(:liked).permit(:restaurant_id, :user_id)
    end
end

app/helpers/likeds_helper.rb
module LikedsHelper
end

app/views/likeds/_form.html.erb
<%= form_with(model: liked, local: true) do |form| %>
  <% if liked.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(liked.errors.count, "error") %> prohibited this liked from being saved:</h2>

      <ul>
      <% liked.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :restaurant_id %>
    <%= form.text_field :restaurant_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/likeds/edit.html.erb
<h1>Editing Liked</h1>

<%= render 'form', liked: @liked %>

<%= link_to 'Show', @liked %> |
<%= link_to 'Back', likeds_path %>

app/views/likeds/index.html.erb
<%= stylesheet_link_tag "style.css" %>
<div class="container">
<div class="card rounded" style="width: 100%; padding:20px; margin: 20px; background: white">
  <div class="card-body">
    <h1 class="card-title">Likes
</h1>
<p id="notice"><%= notice %></p>



<table>
  <thead>
    <tr>
      <th>Restaurant</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @likeds.each do |liked| %>
      <tr>
        <td><%= liked.restaurant_id %></td>
        <td><%= liked.user_id %></td>
        <td><%= link_to 'Show', liked %></td>
        <td><%= link_to 'Edit', edit_liked_path(liked) %></td>
        <td><%= link_to 'Destroy', liked, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Liked', new_liked_path %> |
<%= link_to 'Back', users_path %> |
<%= link_to 'Restaurants', restaurants_path %> |
<%= link_to 'Events', events_path %>

app/views/likeds/new.html.erb
<h1>New Liked</h1>

<%= render 'form', liked: @liked %>

<%= link_to 'Back', likeds_path %>

app/views/likeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Restaurant:</strong>
  <%= @liked.restaurant_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @liked.user_id %>
</p>

<%= link_to 'Edit', edit_liked_path(@liked) %> |
<%= link_to 'Back', likeds_path %>